name: Determine Modified Directory Python
description: Determine if a specific directory has been modified (Python version)

runs:
  using: 'docker'
  container:
    image: python:3.9-slim
  command: |
    python /main.py ${{ inputs.directory }}

inputs:
  directory:
    description: 'The directory to check for modifications'
    required: true

outputs:
  modified:
    description: 'Outputs whether the directory has been modified'
    value: ${{ steps.check-modifications.outputs.modified }}
