name: :rocket:Publish
on:
  push:
    branches: ['main']

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build-and-push-image:
      runs-on: ubuntu-latest
    
    # #Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.

      permissions: write-all
      # permissions:
      #   contents: read
      #   packages: write
      #   #

      steps:
        - name: :open_file_folder:Checkout repository
          uses: actions/checkout@v4
          
        - name: :electric_plug:Login to the Container registry
          uses: docker/login-action@v1
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
  
        - name: :building_construction:Build Image
          run: |
            docker build . --tag ghcr.io/leahlandau/try:latest
            docker push ghcr.io/leahlandau/try:latest


        - name: Pull Docker image from GitHub Container Registry
          run: docker pull ghcr.io/organization/try:latest

        - name: Azure Login
          run: az login

        - name: Configure Docker with Azure Container Registry credentials
          run: az acr login --name try

        - name: Tag the Docker image for Azure Function App
          run: docker tag ghcr.io/leahlandau/try:latest azuretry:latest

        - name: Push Docker image to Azure Container Registry
          run: docker push azuretry:latest

        - name: Deploy Docker image to Azure Function App
          run: |
            az functionapp config container set --name functioapp1 --resource-group myfirstrail --docker-custom-image-name azuretry:latest

        - name: Restart Azure Function App
          run: az functionapp restart --name functioapp1 --resource-group myfirstrail

        # - name: 🔌 Log in to Azure
        #   uses: azure/login@v1
        #   with:
        #     creds: ${{ secrets.AZURE_CREDENTIALS }}
            
        # - name: 🚀 Build and deploy Container App
        #   uses: azure/container-apps-deploy-action@v1
        #   with:
        #     resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
        #     name: ${{ functioapp1 }}
        #     image: ${{ ghcr.io/leahlandau/try:latest }}
        #     registry-username: ${{ github.actor }}
        #     registry-password: ${{ secrets.GITHUB_TOKEN }}

