name: 🚀 Publish

  on:
    push:
      branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
  
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: 📂 Checkout repository
        uses: actions/checkout@v4
        
      - name: 🔌Login to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: 🏗️ Build Image
      #   run: |
      #     docker build . --tag ghcr.io  /skyvar/manage_storage_accounts:latest
      #     docker push ghcr.io/skyvar/manage_storage_accounts:latest
       - name:🏗️ Build and 🫸push image to GitHub Container Registry
         uses: docker/build-push-action@v5
         with:
           context: . 
           push: true
           tags: ghcr.io/leahlandau/try:latest
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: 🚀 deploy Container App
        uses:  Azure/functions-action@v1  
        with:
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          name: ${{ secrets.AZURE_APP_NAME }}
          image: ${{ ghcr.io/leahlandau/try:latest }}
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}