name: :rocket:Publish
on:
  push:
    branches: ['main']

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build-and-push-image:
      runs-on: ubuntu-latest
    
    # #Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.

      permissions: write-all
      # permissions:
      #   contents: read
      #   packages: write
      #   #

      steps:
        - name: :open_file_folder:Checkout repository
          uses: actions/checkout@v4
          
        - name: :electric_plug:Login to the Container registry
          uses: docker/login-action@v1
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
  
        - name: :building_construction:Build Image
          run: |
            docker build . --tag ghcr.io/leahlandau/try:latest
            docker push ghcr.io/leahlandau/try:latest

        - name: 🔌 Log in to Azure
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
            
        - name: 🚀 Build and deploy Container App
          uses: azure/container-apps-deploy-action@v1
          with:
            resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
            name: ${{ functioapp1 }}
            image: ${{ ghcr.io/leahlandau/try:latest }}
            registry-username: ${{ github.actor }}
            registry-password: ${{ secrets.GITHUB_TOKEN }}

# name: 🔖 Echo release  

# on:
#   push:
#     branch:
#     - 'main' 

# jobs:
#   build:
#     name: Upload Release Asset
#     runs-on: ubuntu-latest
#     steps:
#       - name: 🐳 Docker meta
#         id: docker_meta
#         uses: docker/metadata-action@v5
#         with:
#           images: LeahLandau

#       - name: ⬆️ Echo Release latest
#         run: echo "docker tags ${{steps.docker_meta.outputs.tags}}"
        
        
#       - name: 🔌Login to GitHub Container Registry
#         uses: docker/login-action@v1
#         run : echo "name ${{github.actor}} pass ${{secrets.GITHUB_TOKEN}}"
#         with:
#           registry: ghcr.io
#           username: ${{github.actor}}
#           password: ${{secrets.GITHUB_TOKEN}}

#       - name: 🏗️ Build and push
#         uses: docker/build-push-action@v5
#         with:
#           context: .
#           tags: ${{ steps.docker_meta.outputs.tags }}
#           labels: ${{ steps.docker_meta.outputs.labels }}