name: 🚀 Publish Directory

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - directory1
          - directory2

    steps:
      - name: 📂 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔎 Determine modified directory
        id: determine_directory
        run: |
          git diff --name-only HEAD~1 ${{ github.sha }} > changes.txt
          if grep -q '^${{ matrix.directory }}/' changes.txt; then
            echo "${{ matrix.directory }} has changes"
            echo "::set-output name=directory::${{ matrix.directory }}"
          else
            echo "No changes in ${{ matrix.directory }}"
            exit 0
          fi

      - name: 🔑 Login to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: steps.determine_directory.outputs.directory == '${{ matrix.directory }}'

      - name: 🔖 Get release tag name
        id: get_release
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          latest: true
        if: steps.determine_directory.outputs.directory == '${{ matrix.directory }}'

      - name: ♻️ Set correct environment
        run: |
          TAG=${{ steps.get_release.outputs.tag_name }}
          echo "TAG=$TAG" >> "$GITHUB_ENV"
        if: steps.determine_directory.outputs.directory == '${{ matrix.directory }}'

      - name: 🐳 Docker metadata
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/leahlandau/try-${{ matrix.directory }}
          tags: |
            type=semver,pattern={{major}}.{{minor}}.{{patch}},value=${{ env.TAG }}
            type=semver,pattern={{major}}.{{minor}},value=${{ env.TAG }}
            type=semver,pattern={{major}},value=${{ env.TAG }}
          if: steps.determine_directory.outputs.directory == '${{ matrix.directory }}'

      - name: 🏗️ Build Image 
        uses: docker/build-push-action@v5
        with: 
          context: ${{ matrix.directory }}
          tags: ${{ steps.get_release.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}  
        if: steps.determine_directory.outputs.directory == '${{ matrix.directory }}'

      - name: 🔑 Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        if: steps.determine_directory.outputs.directory == '${{ matrix.directory }}'
  # Adjusted this part

      - name: 🚀 Deploy Function App for ${{ matrix.directory }}
        uses: azure/functions-action@v1
        with:
          app-name: ${{ secrets["AZURE_APP_NAME_" + matrix.directory.toUpperCase()] }}
          package: ${{ github.workspace }}/${{ matrix.directory }}/
          publish-profile: ${{ secrets["AZURE_FUNCTIONAPP_PUBLISH_PROFILE_" + matrix.directory.toUpperCase()] }}
        if: steps.determine_directory.outputs.directory == '${{ matrix.directory }}'
