name: Deploy to Azure Function App
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.leahlandau }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker Image from GitHub Container Registry
        run: docker pull ghcr.io/${{ github.repository }}/try:tag

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Deploy to Azure Function App
        run: |
          az functionapp config container set --name ${{ secrets.AZURE_FUNCTIONAPP_NAME }} --resource-group YourResourceGroup --docker-custom-image-name ghcr.io/${{ github.repository }}/try:tag
