name: 🚀 Build and deploy container app to Azure Function App 

on:
  push:
    branches:
      - main
    paths:
      - 'emails/**'
      - 'subscriptions/**'
      # Add more directories here if needed

jobs:
  common-steps:
    runs-on: 'ubuntu-latest'
    outputs:
      changed_directories: ${{ steps.determine_directories.outputs.changed_directories }}
    steps:
      - name: 📂 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔎 Determine modified directories
        id: determine_directories
        run: |
          declare -A changed_dirs=()
          for file in $(git diff --name-only HEAD^ HEAD); do
            if [[ "$file" =~ ^emails/ || "$file" =~ ^subscriptions/ ]]; then
              dir=$(echo "$file" | cut -d'/' -f1,2)
              changed_dirs["$dir"]=1
            fi
          done
          json_array=$(printf '"%s" ' "${!changed_dirs[@]}")
          echo "Changed directories: $json_array"
          echo "::set-output name=changed_directories::[$json_array]"
          
  build-and-deploy:
    runs-on: 'ubuntu-latest'
    needs: common-steps
    strategy:
      matrix:
        directory: ${{fromJson(needs.common-steps.outputs.changed_directories)}}
    
    steps:
      - name: print-name
        run:
          echo ${{matrix.directory}};
          exit 0
