name: 🚀 Publish

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./functionapp1

    permissions:
      contents: read
      packages: write
    
    steps:
     - name: 📂 Checkout repository
       uses: actions/checkout@v4
    
     - name: 🔌Login to the Container registry
       uses: docker/login-action@v1
       with:
         registry: ${{ env.REGISTRY }}
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}


     - name: 🏗️ Build and 🫸push image to GitHub Container Registry
       uses: docker/build-push-action@v5
       with: 
        context: . 
        push: true
        tags: ghcr.io/leahlandau/try:latest
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    # - name: 🔌 Login to Azure
    #     uses: azure/login@v1
    #     with:
    #       creds: ${{ secrets.AZURE_CREDENTIALS }}

     - name: Azure Login
       run: az login

     - name: 🚀 deploy Function App
       uses: azure/functions-action@v1
       with:
        app-name: ${{ secrets.AZURE_APP_NAME }} 
        package: ${{ github.workspace }}/ 
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }} 