name: 🚀 Build and deploy container app to Azure Function App 

on:
  push:
    branches:
      - main
    paths:
      - 'emails/**'
      - 'subscriptions/**'

jobs:
  common-steps:
    runs-on: 'ubuntu-latest'
    outputs:
      changed_directories: ${{ steps.determine_directories.outputs.changed_directories }}
    steps:
      - name: 📂 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔎 Determine modified directories
        id: determine_directories
        run: |   
          changed_files=$(git diff --name-only HEAD^ HEAD)
          paths=(
            'emails'
            'subscriptions'
          )
          declare -A changed_dirs=()
          for file in $changed_files; do
            for path in "${paths[@]}"; do
              if [[ "$file" =~ ^$path/ ]]; then
                dir=$(echo "$file" | cut -d'/' -f1)
                changed_dirs["$dir"]=1
              fi
            done
          done
          json_array=$(printf '"%s"\n' "${!changed_dirs[@]}")
          echo "Changed directories: $json_array"
          echo "::set-output name=changed_directories::$json_array"

  build-and-deploy:
    runs-on: 'ubuntu-latest'
    needs: common-steps
    strategy:
      matrix:
        directory: ${{fromJson(needs.common-steps.outputs.changed_directories)}}
  
    steps:
      - name: print-name
        run: |
          echo ${{matrix.directory}};
          exit 0
