name: Build and deploy container app to Azure Functions - directory20

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          # context: .
          push: true
          tags: 'ghcr.io/leahlandau/try-directory20:${{ github.sha }}'
          file: ./directory20/Dockerfile

  deploy:
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: 'production'
        url: ${{ steps.deploy-to-functions.outputs.app-url }}


      steps:

        - name: 🔑 Azure Login
          run: az login

        - name: Deploy to Azure Functions
          id: deploy-to-functions
          uses: Azure/functions-container-action@v1
          with:
            app-name: directory20
            image: 'ghcr.io/leahlandau/try-directory20:${{ github.sha }}'

          #  - name: Deploy to Azure Functions
        #   id: deploy-to-functions
        #   uses: azure/functions-deploy@v2
        #   with:
        #     app-name: 'directory20'
        #     slot-name: 'production'
        #     publish-profile: ${{ secrets.AzureAppService_PublishProfile_da0ec3ceb44d436e9df6937eb6207c7a }}
        #     images: 'ghcr.io/leahlandau/try-directory20:${{ github.sha }}'
         # - name: 🚀 Deploy to Azure Function App