name: '🌍 Terraform Automation'

on:
  workflow_dispatch:

env:
  TF_VAR_subscription_id: ${{secrets.SUBSCRIPTION_ID}}
  TF_VAR_email_sender: ${{secrets.EMAIL_SENDER}}
  TF_VAR_sender_email_password: ${{secrets.EMAIL_SENDER_PASSWORD}}
  TF_VAR_DOCKER_REGISTRY_SERVER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  TF_VAR_DOCKER_REGISTRY_SERVER_USERNAME: ${{ github.actor }}
  TF_VAR_DOCKER_REGISTRY_SERVER_URL: https://ghcr.io
  ARM_SUBSCRIPTION_ID: ${{secrets.SUBSCRIPTION_ID}}
  ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
  ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
  ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 🧩 HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.0
      
      - name: 🔑 Login to Azure
        id : az-login
        run : az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID   

      - name: 🏗️ Terraform Init
        id: init
        run: |
          cd emails/terraform   
          terraform init -input=false

      # - name: 📋 Terraform Plan
      #   id: plan
      #   run: |
      #     cd emails/terraform  
      #     terraform plan -out=tfplan -input=false

      # - name: ✅ Terraform Apply
      #   id: apply
      #   run: |
      #     cd emails/terraform  
      #     terraform apply -input=false -auto-approve tfplan
          

      - name: ✅ Terraform Destroy
        id: apply
        run: |
          cd emails/terraform  
          terraform destroy -auto-approve 


          