# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Functioapp1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://trydeploytofunctionapp.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_a943d3fece1f4096a7f822a537a3da82 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_aec3acc7fdd44388ba6faee4367cd84c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: trydeploytofunctionapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a943d3fece1f4096a7f822a537a3da82 }}/azuretry:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Functioapp1'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7d49a9108c9f4962823a767332fe8cb1 }}
        images: 'trydeploytofunctionapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a943d3fece1f4096a7f822a537a3da82 }}/azuretry:${{ github.sha }}'