# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - directory9

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2
      uses: actions/checkout@v4
              with:
                fetch-depth: 0

    - name: 🔎 Determine modified directory 1
       id: determine_directory1
       run: |
         git diff --name-only HEAD~1 ${{ github.sha }} > changes.txt
         if grep -q '^directory1/' changes.txt; then
           echo "Directory 1 has changes"
           echo "::set-output name=directory::directory1"
         else
           echo "No changes in Directory 1"
           exit 0
         fi

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      if: steps.determine_directory1.outputs.directory == 'directory1'

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      if: steps.determine_directory1.outputs.directory == 'directory1'


    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        context: ./directory9
        push: true
        tags: ghcr.io/leahlandau/try-directory9:${{ github.sha }}
        file: ./directory9/Dockerfile
      if: steps.determine_directory1.outputs.directory == 'directory1'

    # - name: run locally
    #   run: docker run -p 8181:80 ghcr.io/leahlandau/try-directory9:${{ github.sha }}


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.app-url }}

    steps:
     
    - name: 🔑 Azure Login
      run: az login
      if: steps.determine_directory1.outputs.directory == 'directory1'

    # - name: Deploy to Azure Web App
    #   id: deploy-to-webapp
    #   uses: azure/webapps-deploy@v2
    #   with:
    #     app-name: 'directory9'
    #     slot-name: 'production'
    #     publish-profile: ${{ secrets.AzureAppService_PublishProfile_da34fe16f77d4f80b2403cf72d4f4b19 }}
    #     images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_b1c31551a4bb440c9121e9a0a3a08145 }}/leahlandau/try-directory9:${{ github.sha }}'

    - name: Deploy to Azure Functions
      id: deploy-to-functions
      uses: Azure/functions-container-action@v1
      with:
        app-name: directory9
        image: 'ghcr.io/leahlandau/try-directory9:${{ github.sha }}'
      if: steps.determine_directory1.outputs.directory == 'directory1'
