name: 🚀 Publish Directories

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DIRECTORIES: 'directory1,directory2'  # Add more directories separated by comma

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ${{ env.DIRECTORIES }}  # Matrix strategy for multiple directories
    steps:
      - name: 📂 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🚀 Determine modified directory
        id: determine_directory
        run: |
          git diff --name-only HEAD~1 ${{ github.sha }} > changes.txt
          if grep -q '^${{ matrix.directory }}/' changes.txt; then
            echo "${{ matrix.directory }} has changes"
            echo "::set-output name=directory::${{ matrix.directory }}"
          else
            echo "No changes in ${{ matrix.directory }}"
            exit 0
          fi

      - name: 🔑 Login to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: steps.determine_directory.outputs.directory == matrix.directory

      - name: 🏗️ Build and 🫸 push image to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          context: ${{ steps.determine_directory.outputs.directory }}
          push: true
          tags: ghcr.io/leahlandau/${{ matrix.directory }}:latest
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: steps.determine_directory.outputs.directory == matrix.directory

      - name: 🔌 Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 🚀 Deploy Function App for Directory
        run: |
          case "${{ matrix.directory }}" in
            'directory1')
              APP_NAME="${{ secrets.AZURE_APP_NAME_directory1 }}"
              PUBLISH_PROFILE="${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_directory1 }}"
              ;;
            'directory2')
              APP_NAME="${{ secrets.AZURE_APP_NAME_directory2 }}"
              PUBLISH_PROFILE="${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_directory2 }}"
              ;;
            *) echo "Unknown directory: ${{ matrix.directory }}"; exit 1 ;;
          esac

          azure/functions-action@v1 :
            with:
              app-name: ${{ APP_NAME }}
              package: ${{ github.workspace }}/${{ matrix.directory }}/
              publish-profile: ${{ PUBLISH_PROFILE }}
        if: steps.determine_directory.outputs.directory == matrix.directory
